config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users do
    get :employer_details, on: :member
  end

  resources :employments, only: [:new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employment.rb
class Employment < ApplicationRecord
  has_many :users
  validates_uniqueness_of :employer
  validates_presence_of :employer, :start_date, :end_date
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :employment, optional: true
  validates_uniqueness_of :email
  validates_presence_of :email, :first_name, :last_name, :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_action :find_user, only: :create

  # POST /employments or /employments.json

  def new
    @employment = Employment.new
  end

  def create
    @employment = Employment.new(employment_params)
    if @employment.save
      @user.update(employment_id: @employment.id)
      flash.now[:notice] = "Employment was successfully created." 
      render turbo_stream: turbo_stream.replace("flash", partial: "layouts/flash")
    else
      render turbo_stream: turbo_stream.replace(
        'modal',
        partial: 'employments/form',
        locals: {
          user: @user,
          employment: @employment
        }
      ), status: :unprocessable_entity
    end
  end

  private
    def find_user
      @user = User.find(params.dig(:employment, :user_id))
    end

    # Only allow a list of trusted parameters through.
    def employment_params
      params.require(:employment).permit(:employer, :start_date, :end_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :employer_details

  # GET /users or /users.json
  def index
    @users = User.includes(:employment)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def employer_details
    @employment = @user.employment
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      render turbo_stream: [
        turbo_stream.append(
          'users',
          partial: 'user',
          locals: {
            user: @user,
          }
        ),
        turbo_stream.replace(
          'modal',
          partial: 'employments/form',
          locals: {
            user: @user,
            employment: Employment.new
          }
        ),
        turbo_stream.remove("no_records_found")
      ]
    else
      render turbo_stream: turbo_stream.replace(
        'errors',
        partial: 'users/errors',
        locals: {
          user: @user
        }
      ), status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name,:nick_name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def options_for_users
    User.where(employment_id: nil)
      .collect {|p| [ p.first_name, p.id ] }
  end
end

app/views/employments/_errors.html.slim
- if employment.errors.any?
  .bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
    ul
      - employment.errors.each do |error|
        li
          = error.full_message

app/views/employments/_form.html.slim
 = render "shared/modal" do 
  = form_with(model: employment, url: employments_path, class: "contents", data: { controller: "employment" }) do |form|
    = turbo_frame_tag "errors" do
      = render "errors", employment: employment
    .my-5
      = form.label :employer
      = form.text_field :employer, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: 'focusout->employment#validateRequiredField', target: 'employment.employer'}
    .my-5
      = form.label :start_date
      = form.date_field :start_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: 'focusout->employment#validateStartDateField', target: 'employment.startDate'}
    .my-5
      = form.label :end_date
      = form.date_field :end_date, "datepicker-format": "mm/dd/yyyy", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: 'focusout->employment#validateEndDateField', target: 'employment.endDate'}
    .my-5
      = form.hidden_field :user_id, value: user.id, data: { target: 'employment.startDate'}
    .inline
      = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: { target: 'employment.submitBtn'}

app/views/employments/_user_employment.html.slim
= form_with(model: employment, url: employments_path, class: "contents", data: { controller: "employment" }) do |form|
  = turbo_frame_tag "errors" do
    = render "errors", employment: employment
  .my-5
    = form.label :employer
    = form.text_field :employer, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: 'focusout->employment#validateRequiredField', target: 'employment.employer'}
  .my-5
    = form.label :start_date
    = form.date_field :start_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", format: "mm/dd/yyyy", data: { action: 'focusout->employment#validateStartDateField', target: 'employment.startDate'}
  .my-5
    = form.label :end_date
    = form.date_field :end_date, "datepicker-format": "mm/dd/yyyy", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: 'focusout->employment#validateEndDateField', target: 'employment.endDate'}
  .my-5
    = form.label 'Select an user'
    = form.select :user_id, options_for_users, { include_blank: false }, { class: "border border-gray-200 outline-none px-3 py-2 mt-2 w-full" }
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: { target: 'employment.submitBtn'}

app/views/employments/new.html.slim
= render "shared/modal" do
  = render "user_employment", employment: @employment

app/views/layouts/_flash.html.slim
- flash.each do |flash_type, message|
  .p-4.mb-4.text-sm.text-green-700.bg-green-100.rounded-lg.dark:bg-green-200.dark:text-green-800[role="alert"]
    span.font-medium
      = message

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | HotwireModal
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = render "layouts/header"
    main.container.mx-auto.mt-28.px-5.flex.flex-col
      = turbo_frame_tag "modal"
      = turbo_frame_tag "flash" do
        = render "layouts/flash"
      = yield

app/views/shared/_modal.html.slim
= turbo_frame_tag "modal" do
  = content_tag('div', :class=>"fixed z-10 inset-0 overflow-y-auto animated fadeIn flex items-center justify-center", :style=>"z-index:9999", id: "turbo-modal")
    = tag.div data: { controller: "turbo-modal", action: "turbo:submit-end->turbo-modal#handleSuccess"}, style: "padding: 30px;" do
      .flex.items-end.justify-center.min-h-screen.pt-4.px-4.pb-20.text-center.lg:block.lg:p-0
          .fixed.inset-0.bg-gray-500.bg-opacity-75.transition-opacity
            .h-screen.px-4.flex.items-center.justify-center
              .bg-white class="md:max-w-[130%]"
                .flex.justify-between
                  h1.text-gray-800.font-semibold.text-xl.text-left.px-6.pt-6.pb-6#modal_title
                  = button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "bg-white rounded-md p-2 inline-flex tems-center justify-center.text-gray-400 hover:text-gray-500 hover:bg-gray-100.focus:outline-none focus:ring-2.focus:ring-inset focus:ring-indigo-500"
                    span.sr-only
                      Close menu
                    svg.h-6.w-6[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke="currentColor" aria-hidden="true"]
                      path[stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"]      
                .px-6.pb-6.text-left.w-full.overflow-y-auto style="max-height: calc(100vh - 120px)"
                  = yield
                  = button_tag "Cancel", data: { action: "turbo-modal#hideModal"  }, type: "button", class: "w-40 rounded-lg py-3 px-3  ml-5 w-full bg-blue-600 text-white text-center font-medium cursor-pointer"

app/views/users/_errors.html.slim
- if user.errors.any?
  .bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
    ul
      - user.errors.each do |error|
        li
          = error.full_message

app/views/users/_form.html.slim
= render "shared/modal" do
  = form_with(model: user, class: "contents", data: { controller: "users", target: 'users.form' }) do |form|
    = turbo_frame_tag "errors" do
      = render "errors", user: user
    .my-5
      = form.label :first_name
      = form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full required", data: { action: 'focusout->users#validateRequiredField', target: 'users.firstName'}
    .my-5
      = form.label :last_name
      = form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: 'focusout->users#validateRequiredField', target: 'users.lastName'}
    .my-5
      = form.label :nick_name
      = form.text_field :nick_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
    .my-5
      = form.label :email
      = form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: 'focusout->users#validateEmail', target: 'users.email'}
    .my-5
      = form.label :phone
      = form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: 'focusout->users#validatePhone', target: 'users.phone', mask: '(999) 999-9999' }
    .inline
      = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: { target: 'users.submitBtn'}

app/views/users/_no_records.html.slim
tr#no_records_found[is="turbo-frame"]
  td.max-w-lg.justify-between.items-center
    .h-48.lg:h-auto.lg:w-48.flex-none.bg-cover.rounded-t.lg:rounded-t-none.lg:rounded-l.text-center.overflow-hidden[style="background-image: url('/img/card-left.jpg')" title="Woman holding a mug"]
    .border-gray-400.lg:border-gray-400.bg-white.rounded-b.lg:rounded-b-none.lg:rounded-r.p-4.flex.flex-col.justify-between.leading-normal
      .mb-8
        .text-gray-900.font-bold.text-xl.mb-2
          | No Records Found!
        p.text-gray-700.text-base
          | Please Click on Personal Data to add users and employer

app/views/users/_user.html.slim
tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700.hover:bg-gray-50.dark:hover:bg-gray-600 
  td.py-4.px-6
    =user.first_name
  td.py-4.px-6
    =user.last_name
  td.py-4.px-6
    =user.email
  td.py-4.px-6
    =user.phone
  td.py-4.px-6
    - if user.employment.present?
      =link_to "View Employer", employer_details_user_path(user.id), data: { turbo_frame: 'modal' }

app/views/users/employer_details.html.slim
= render "shared/modal" do
  .max-w-lg.justify-between.items-center
    .h-48.lg:h-auto.lg:w-48.flex-none.bg-cover.rounded-t.lg:rounded-t-none.lg:rounded-l.text-center.overflow-hidden[style="background-image: url('/img/card-left.jpg')" title="Woman holding a mug"]
    .border-gray-400.lg:border-gray-400.bg-white.rounded-b.lg:rounded-b-none.lg:rounded-r.p-4.flex.flex-col.justify-between.leading-normal
      .mb-8
        .text-gray-900.font-bold.text-xl.mb-2
          | Employer Details
        .flex.flex-col
            p.text-gray-700.text-base.mb-2
              span.font-bold
                | Name: 
              =@employment.employer
            p.text-gray-700.text-base.mb-2
              span.font-bold
                |Start Date: 
              =@employment.start_date
            p.text-gray-700.text-base
              span.font-bold
                |End Date: 
              =@employment.end_date

app/views/users/index.html.slim
.bg-white.w-full.h-full.rounded.overflow-auto
  .grid.grid-cols-6.justify-between.items-center.pb-4
    = link_to "Personal Data", new_user_path, data: { turbo_frame: 'modal' }, class: "w-40 rounded-lg py-3 px-3  w-full bg-blue-600 text-white text-center font-medium cursor-pointer"
    = link_to "Employment", new_employment_path, data: { turbo_frame: 'modal' }, class: "w-40 rounded-lg py-3 px-3  w-full bg-blue-600 text-white text-center font-medium cursor-pointer"
  table.w-full.text-sm.text-left.text-gray-500.dark:text-gray-400.mb-2
    thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
      tr
        th.py-3.px-6[scope="col"]
          | First Name
        th.py-3.px-6[scope="col"]
          | Last Name
        th.py-3.px-6[scope="col"]
          | Email
        th.py-3.px-6[scope="col"]
          | Phone
        th.py-3.px-6[scope="col"]
          | Employer
    tbody#users[is="turbo-frame"]
      - if @users.blank?
        = render partial: 'no_records'
      - @users.each do |user|
        = render partial: 'user', locals: { user: user }

app/views/users/new.html.slim
= render "form", user: @user